package bcr

import (
	"context"
	"flag"
	"fmt"
	"log"
	"maps"
	"os"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
	"github.com/dominikbraun/graph"
	"github.com/google/go-github/v66/github"
	bzpb "github.com/stackb/centrl/build/stack/bazel/bzlmod/v1"
	"github.com/stackb/centrl/pkg/gh"
	gitpkg "github.com/stackb/centrl/pkg/git"
	"github.com/stackb/centrl/pkg/metadatajson"
	"github.com/stackb/centrl/pkg/modulebazel"
	"github.com/stackb/centrl/pkg/protoutil"
)

// stringBoolMap is a custom flag type for repeatable string flags that populates a map
type stringBoolMap map[string]bool

func (m *stringBoolMap) String() string {
	if *m == nil {
		return ""
	}
	urls := make([]string, 0, len(*m))
	for url := range *m {
		urls = append(urls, url)
	}
	return strings.Join(urls, ",")
}

func (m *stringBoolMap) Set(value string) error {
	if *m == nil {
		*m = make(map[string]bool)
	}
	(*m)[value] = true
	return nil
}

// NewLanguage is called by Gazelle to install this language extension in a
// binary.
func NewLanguage() language.Language {
	return &bcrExtension{
		depGraph:          initDepGraph(),
		regularDepGraph:   initDepGraph(),
		devDepGraph:       initDepGraph(),
		moduleToCycle:     make(map[string]string),
		unresolvedModules: make(map[string]bool),
		repositories:      make(map[string]*bzpb.RepositoryMetadata),
		docUrls:           make(map[string][]*rule.Rule),
		sourceUrls:        make(map[string][]*rule.Rule),
		modules:           make(map[string]*rule.Rule),
		moduleVersions:    make(map[string]*rule.Rule),
	}
}

// bcrExtension implements language.Language.
type bcrExtension struct {
	name                  string
	depGraph              graph.Graph[string, string] // graph of all dependencies (regular + dev) - for cycle detection
	regularDepGraph       graph.Graph[string, string] // graph of only non-dev dependencies
	devDepGraph           graph.Graph[string, string] // graph of only dev dependencies
	registryRoot          string
	registryURL           string
	repoRoot              string // copy of config.RepoRoot
	modulesRoot           string
	baseRegistryFile      string
	resourceStatusSetFile string
	githubToken           string
	gitlabToken           string
	moduleToCycle         map[string]string                   // maps "module@version" to cycle rule name
	unresolvedModules     map[string]bool                     // tracks "module@version" keys that failed to resolve
	repositories          map[string]*bzpb.RepositoryMetadata // tracks unique repository strings (e.g., "github:org/repo")
	modules               map[string]*rule.Rule               // tracks module metadata rules
	moduleVersions        map[string]*rule.Rule               // tracks module_version rules by "module@version" key
	docUrls               map[string][]*rule.Rule             // tracks docs http_archives to fetch (e.g.  https://github.com/bazel-contrib/yq.bzl/releases/download/v0.3.2/yq.bzl-v0.3.2.docs.tar.gz -> http_archive rule)
	sourceUrls            map[string][]*rule.Rule             // tracks docs starlark_repository
	resourceStatus        map[string]*bzpb.ResourceStatus     // results of reading resourceStatusSetFile, keyed by URL
	blacklistedUrls       stringBoolMap                       // tracks urls that are known to have wrong integrity
	baseRegistry          *bzpb.Registry
	moduleCommits         map[string]*bzpb.ModuleCommit // cache of all module commits (preloaded)
	githubClient          *github.Client
	mvsResult             *mvsResult // Minimum Version Selection results
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (ext *bcrExtension) Name() string {
	return bcrLangName
}

// The following methods are implemented to satisfy the
// https://pkg.go.dev/github.com/bazelbuild/bazel-gazelle/resolve?tab=doc#Resolver
// interface, but are otherwise unused.
func (ext *bcrExtension) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
	fs.StringVar(&ext.registryRoot, "registry-root", "", "root dir for the bcr registry")
	fs.StringVar(&ext.registryURL, "registry-url", "", "base URL for the deployed registry")
	fs.StringVar(&ext.resourceStatusSetFile, "resource-status-set-file", "", "path to resource-status.pb file containing cached http statuses for the registry URLs (helpful for development)")
	fs.StringVar(&ext.baseRegistryFile, "registry-file", "", "path to repository.pb file containing registry data to use as a base data set (repository metadata)")
	fs.StringVar(&ext.githubToken, "github-token", os.Getenv("GITHUB_TOKEN"), "GitHub API token (defaults to GITHUB_TOKEN env var)")
	fs.StringVar(&ext.gitlabToken, "gitlab-token", os.Getenv("GITLAB_TOKEN"), "GitLab API token (defaults to GITLAB_TOKEN env var)")
	fs.Var(&ext.blacklistedUrls, "blacklisted_url", "URL to blacklist (repeatable)")
}

func (ext *bcrExtension) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	ext.repoRoot = c.RepoRoot

	// ensure registryRoot has been set
	if ext.registryRoot == "" {
		return fmt.Errorf("--registry-root is required")
	}
	if ext.registryURL == "" {
		return fmt.Errorf("--registry-url is required")
	}
	ext.modulesRoot = filepath.Join(ext.registryRoot, "modules")

	if ext.githubToken != "" {
		ext.githubClient = gh.NewClient(ext.githubToken)
	} else {
		log.Printf("No github-token available.  GitHub API operations will be disabled.")
	}

	ext.baseRegistry = &bzpb.Registry{}
	if ext.baseRegistryFile != "" {
		if err := protoutil.ReadFile(os.ExpandEnv(ext.baseRegistryFile), ext.baseRegistry); err != nil {
			return err
		}
	}
	ext.resourceStatus = make(map[string]*bzpb.ResourceStatus)
	if ext.resourceStatusSetFile != "" {
		var resourceStatusSet bzpb.ResourceStatusSet
		if err := protoutil.ReadFile(os.ExpandEnv(ext.resourceStatusSetFile), &resourceStatusSet); err != nil {
			log.Printf("warning: could not read resource statuses: %v", err)
		}
		for _, status := range resourceStatusSet.Status {
			ext.resourceStatus[status.Url] = status
		}
	}

	// Preload all module commits in one git call for performance
	ctx := context.Background()
	submodulePath := filepath.Join(c.RepoRoot, ext.registryRoot)
	log.Printf("Preloading module commits from %s...", submodulePath)
	commits, err := gitpkg.GetAllModuleCommits(ctx, submodulePath, "modules/*/*/MODULE.bazel")
	if err != nil {
		log.Printf("warning: failed to preload module commits: %v", err)
		ext.moduleCommits = make(map[string]*bzpb.ModuleCommit)
	} else {
		ext.moduleCommits = commits
		log.Printf("Preloaded %d module commits", len(commits))
	}

	return nil
}

// Configure implements config.Configurer
func (ext *bcrExtension) Configure(c *config.Config, rel string, f *rule.File) {
	// log.Println("visiting:", rel)
	cfg := getOrCreateConfig(c)

	// enable this extension once we hit the registry
	if ext.registryRoot == rel {
		cfg.enabled = true
	}
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (*bcrExtension) Kinds() map[string]rule.KindInfo {
	kinds := map[string]rule.KindInfo{}
	maps.Copy(kinds, moduleMetadataKinds())
	maps.Copy(kinds, moduleMaintainerKinds())
	maps.Copy(kinds, moduleVersionKinds())
	maps.Copy(kinds, moduleCommitKinds())
	maps.Copy(kinds, moduleDependencyKinds())
	maps.Copy(kinds, moduleSourceKinds())
	maps.Copy(kinds, moduleAttestationsKinds())
	maps.Copy(kinds, modulePresubmitKinds())
	maps.Copy(kinds, moduleDependencyCycleKinds())
	maps.Copy(kinds, moduleRegistryKinds())
	maps.Copy(kinds, gitOverrideKinds())
	maps.Copy(kinds, archiveOverrideKinds())
	maps.Copy(kinds, singleVersionOverrideKinds())
	maps.Copy(kinds, localPathOverrideKinds())
	maps.Copy(kinds, repositoryMetadataKinds())
	return kinds
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (ext *bcrExtension) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		moduleMetadataLoadInfo(),
		moduleMaintainerLoadInfo(),
		moduleVersionLoadInfo(),
		moduleCommitLoadInfo(),
		moduleDependencyLoadInfo(),
		moduleSourceLoadInfo(),
		moduleAttestationsLoadInfo(),
		modulePresubmitLoadInfo(),
		moduleDependencyCycleLoadInfo(),
		moduleRegistryLoadInfo(),
		gitOverrideLoadInfo(),
		archiveOverrideLoadInfo(),
		singleVersionOverrideLoadInfo(),
		localPathOverrideLoadInfo(),
		repositoryMetadataLoadInfo(),
	}
}

func (*bcrExtension) KnownDirectives() (directives []string) {
	return
}

// Fix repairs deprecated usage of language-specific rules in f. This is called
// before the file is indexed. Unless c.ShouldFix is true, fixes that delete or
// rename rules should not be performed.
func (*bcrExtension) Fix(c *config.Config, f *rule.File) {
}

// Imports returns a list of ImportSpecs that can be used to import the rule r.
// This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (ext *bcrExtension) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	switch r.Kind() {
	case "module_version":
		return moduleVersionImports(r)
	case "module_metadata":
		return moduleMetadataImports(r)
	case "git_override":
		return gitOverrideImports(r)
	case "archive_override":
		return archiveOverrideImports(r)
	case "single_version_override":
		return singleVersionOverrideImports(r)
	case "local_path_override":
		return localPathOverrideImports(r)
	case "repository_metadata":
		return repositoryMetadataImports(r)
	}
	return nil
}

// Embeds returns a list of labels of rules that the given rule embeds. If a
// rule is embedded by another importable rule of the same language, only the
// embedding rule will be indexed. The embedding rule will inherit the imports
// of the embedded rule. Since SkyLark doesn't support embedding this should
// always return nil.
func (*bcrExtension) Embeds(r *rule.Rule, from label.Label) []label.Label {
	return nil
}

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each rule
// generated by language.GenerateRules in language.GenerateResult.Imports.
// Resolve generates a "deps" attribute (or the appropriate language-specific
// equivalent) for each import according to language-specific rules and
// heuristics.
func (ext *bcrExtension) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	importsRaw any,
	from label.Label,
) {
	// Switch on rule kind to delegate to specific resolver functions
	switch r.Kind() {
	case "module_dependency":
		resolveModuleDependencyRule(ext.modulesRoot, r, ix, from, ext.moduleToCycle, ext.unresolvedModules)
	case "module_dependency_cycle":
		resolveModuleDependencyCycleRule(r, ix)
	case "module_metadata":
		resolveModuleMetadataRule(r, ix)
	case "module_registry":
		resolveModuleRegistryRule(r, ix)
	case "module_source":
		resolveModuleSourceRule(r, c, from)
	case "repository_metadata":
		resolveRepositoryMetadataRule(r, ix, ext.repositories)
	case "module_version":
		resolveModuleVersionRule(r, ext.modules)
	}
}

// GenerateRules extracts build metadata from source files in a directory.
// GenerateRules is called in each directory where an update is requested in
// depth-first post-order.
//
// args contains the arguments for GenerateRules. This is passed as a struct to
// avoid breaking implementations in the future when new fields are added.
//
// A GenerateResult struct is returned. Optional fields may be added to this
// type in the future.
//
// Any non-fatal errors this function encounters should be logged using
// log.Print.
func (ext *bcrExtension) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	cfg := mustGetConfig(args.Config)
	if !cfg.enabled {
		return language.GenerateResult{}
	}

	// log.Println("visiting:", args.Rel, args.RegularFiles)

	var rules []*rule.Rule

	// Generate repository metadata in the registry root package
	if args.Rel == ext.registryRoot {
		repoRules := makeRepositoryMetadataRules(ext.repositories)
		rules = append(rules, repoRules...)
	}

	// Generate cycles and the module registry in the modules root package
	if args.Rel == ext.modulesRoot {
		cycles := ext.getCycles()
		var cycleRules []*rule.Rule
		if len(cycles) > 0 {
			cycleRules = makeModuleDependencyCycleRules(cycles)
			rules = append(rules, cycleRules...)
		}
		rules = append(rules, makeModuleRegistryRule(path.Base(args.Rel), args.Subdirs, ext.registryURL, cycleRules, args.Config))
	}

	// create module_metadata rule in the module root
	if slices.Contains(args.RegularFiles, "metadata.json") {
		filename := filepath.Join(args.Config.WorkDir, args.Rel, "metadata.json")
		md, err := metadatajson.ReadFile(filename)
		if err != nil {
			log.Fatalf("reading %s/source.json: %v", args.Rel, err)
		}
		// Generate maintainer rules
		maintainerRules := makeModuleMaintainerRules(md.Maintainers)
		// Add maintainer rules to the list
		rules = append(rules, maintainerRules...)
		// Add metadata rule with references to maintainers (passing ext to track repositories)
		r := makeModuleMetadataRule(path.Base(args.Rel), md, maintainerRules, "metadata.json", ext)
		// track it so moduleVersion can determine if it is latest version
		ext.modules[r.Name()] = r
		rules = append(rules, r)
	}

	// are we in a module version directory?
	if !inOverlayDir(args.Rel) && slices.Contains(args.RegularFiles, "MODULE.bazel") {
		// The BCR should not contain BUILD.bazel files in the same directory as
		// the MODULE.bazel file, these should exist as patches or overlays.
		// However, at least one exists which references @rules_cc, and as a
		// consequence we cannot build.  If this file exists, remove all
		// pre-existing rules if a BUILD file exists.
		if args.File != nil {
			for _, r := range args.File.Rules {
				r.Delete()
			}
			args.File.Sync()
		}

		moduleBazelFilename := filepath.Join(args.Config.WorkDir, args.Rel, "MODULE.bazel")
		module, err := modulebazel.ExecFile(moduleBazelFilename)
		if err != nil {
			log.Fatalf("reading %s: %v", moduleBazelFilename, err)
		}

		// Extract version from path (e.g., modules/foo/1.2.3 -> 1.2.3)
		version := filepath.Base(args.Rel)

		var sourceRule *rule.Rule
		var attestationsRule *rule.Rule
		var presubmitRule *rule.Rule
		var commitRule *rule.Rule

		// Create module_commit rule with git metadata using preloaded cache
		commit, err := makeModuleVersionCommitRule(args.Config, ext.registryRoot, args.Rel, ext.moduleCommits)
		if err != nil {
			log.Printf("warning: failed to create commit rule for %s: %v", args.Rel, err)
		} else {
			commitRule = commit
			rules = append(rules, commitRule)
		}

		if slices.Contains(args.RegularFiles, "source.json") {
			sourceFilename := filepath.Join(args.Config.WorkDir, args.Rel, "source.json")
			source, err := readModuleSourceJson(sourceFilename)
			if err != nil {
				log.Fatalf("reading %s/source.json: %v", args.Rel, err)
			}
			module.Source = source
			sourceRule = makeModuleSourceRule(module, source, "source.json", ext)
			rules = append(rules, sourceRule)
		}

		if slices.Contains(args.RegularFiles, "attestations.json") {
			// Try to read attestations.json if it exists
			attestationsFilename := filepath.Join(args.Config.WorkDir, args.Rel, "attestations.json")
			attestations, err := readAttestationsJson(attestationsFilename)
			if err != nil {
				log.Fatalf("reading %s/attestations.json: %v", args.Rel, err)
			}
			module.Attestations = attestations
			attestationsRule = makeModuleAttestationsRule(attestations, "attestations.json")
			rules = append(rules, attestationsRule)
		}

		if slices.Contains(args.RegularFiles, "presubmit.yml") {
			// Try to read presubmit.yml if it exists
			presubmitFilename := filepath.Join(args.Config.WorkDir, args.Rel, "presubmit.yml")
			presubmit, err := readPresubmitYaml(presubmitFilename)
			if err != nil {
				log.Printf("reading %s/presubmit.yml: %v", args.Rel, err)
			}
			module.Presubmit = presubmit
			presubmitRule = makeModulePresubmitRule(presubmit, "presubmit.yml")
			rules = append(rules, presubmitRule)
		}

		// Add module to all dependency graphs
		moduleKey := fmt.Sprintf("%s@%s", module.Name, version)
		ext.addModuleToGraph(module.Name, version)
		_ = ext.regularDepGraph.AddVertex(moduleKey)
		_ = ext.devDepGraph.AddVertex(moduleKey)

		// Add dependency edges to graphs
		for _, dep := range module.Deps {
			// Add to main graph (all deps - for cycle detection)
			ext.addDependencyEdge(module.Name, version, dep.Name, dep.Version)

			fromKey := fmt.Sprintf("%s@%s", module.Name, version)
			toKey := fmt.Sprintf("%s@%s", dep.Name, dep.Version)

			if dep.Dev {
				// Add to dev graph only
				_ = ext.devDepGraph.AddVertex(fromKey)
				_ = ext.devDepGraph.AddVertex(toKey)
				_ = ext.devDepGraph.AddEdge(fromKey, toKey)
			} else {
				// Add to regular graph only
				_ = ext.regularDepGraph.AddVertex(fromKey)
				_ = ext.regularDepGraph.AddVertex(toKey)
				_ = ext.regularDepGraph.AddEdge(fromKey, toKey)
			}
		}

		// Generate dependency and override rules
		depRules, overrideRules := makeModuleDependencyRules(module.Deps)
		// Add override rules to the list first (so dependencies can reference
		// them)
		rules = append(rules, overrideRules...)
		// Add dependency rules to the list
		rules = append(rules, depRules...)
		// Add module version rule with references to dependencies, source,
		// attestations, presubmit, and commit
		moduleVersionRule := makeModuleVersionRule(module, version, depRules, sourceRule, attestationsRule, presubmitRule, commitRule, "MODULE.bazel")
		rules = append(rules, moduleVersionRule)

		// Track the module_version rule for later MVS annotation
		ext.moduleVersions[moduleKey] = moduleVersionRule
	}

	imports := make([]interface{}, len(rules))
	for i, r := range rules {
		imports[i] = r.PrivateAttr(config.GazelleImportsKey)
	}

	return language.GenerateResult{
		Gen:     rules,
		Imports: imports,
	}
}

func inOverlayDir(rel string) bool {
	return strings.Contains(rel, "/overlay")
}
