package bcr

import (
	"flag"
	"log"
	"maps"
	"path"
	"path/filepath"
	"slices"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
	"github.com/dominikbraun/graph"
	"github.com/stackb/centrl/pkg/modulebazel"
)

// NewLanguage is called by Gazelle to install this language extension in a
// binary.
func NewLanguage() language.Language {
	return &bcrExtension{
		depGraph:      initDepGraph(),
		moduleToCycle: make(map[string]string),
	}
}

// bcrExtension implements language.Language.
type bcrExtension struct {
	name          string
	depGraph      graph.Graph[string, string]
	modulesRoot   string
	moduleToCycle map[string]string // maps "module@version" to cycle rule name
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (ext *bcrExtension) Name() string {
	return bcrLangName
}

// The following methods are implemented to satisfy the
// https://pkg.go.dev/github.com/bazelbuild/bazel-gazelle/resolve?tab=doc#Resolver
// interface, but are otherwise unused.
func (ext *bcrExtension) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
	fs.StringVar(&ext.modulesRoot, "modules-root", "modules", "root package dir of the bcr modules")
}

func (*bcrExtension) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	return nil
}

func (*bcrExtension) KnownDirectives() []string {
	return []string{bcrModulesRootDirective}
}

// Configure implements config.Configurer
func (ext *bcrExtension) Configure(c *config.Config, rel string, f *rule.File) {
	cfg := getOrCreateConfig(c, rel)
	if f != nil {
		cfg.parseDirectives(rel, f.Directives)
	}
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (*bcrExtension) Kinds() map[string]rule.KindInfo {
	kinds := map[string]rule.KindInfo{}
	maps.Copy(kinds, moduleMetadataKinds())
	maps.Copy(kinds, moduleMaintainerKinds())
	maps.Copy(kinds, moduleVersionKinds())
	maps.Copy(kinds, moduleDependencyKinds())
	maps.Copy(kinds, moduleSourceKinds())
	maps.Copy(kinds, moduleAttestationsKinds())
	maps.Copy(kinds, modulePresubmitKinds())
	maps.Copy(kinds, moduleDependencyCycleKinds())
	maps.Copy(kinds, moduleRegistryKinds())
	maps.Copy(kinds, gitOverrideKinds())
	maps.Copy(kinds, archiveOverrideKinds())
	maps.Copy(kinds, singleVersionOverrideKinds())
	maps.Copy(kinds, localPathOverrideKinds())
	return kinds
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (ext *bcrExtension) Loads() []rule.LoadInfo {
	return []rule.LoadInfo{
		moduleMetadataLoadInfo(),
		moduleMaintainerLoadInfo(),
		moduleVersionLoadInfo(),
		moduleDependencyLoadInfo(),
		moduleSourceLoadInfo(),
		moduleAttestationsLoadInfo(),
		modulePresubmitLoadInfo(),
		moduleDependencyCycleLoadInfo(),
		moduleRegistryLoadInfo(),
		gitOverrideLoadInfo(),
		archiveOverrideLoadInfo(),
		singleVersionOverrideLoadInfo(),
		localPathOverrideLoadInfo(),
	}
}

// Fix repairs deprecated usage of language-specific rules in f. This is called
// before the file is indexed. Unless c.ShouldFix is true, fixes that delete or
// rename rules should not be performed.
func (*bcrExtension) Fix(c *config.Config, f *rule.File) {
}

// Imports returns a list of ImportSpecs that can be used to import the rule r.
// This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (ext *bcrExtension) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	switch r.Kind() {
	case "module_version":
		return moduleVersionImports(r)
	case "module_metadata":
		return moduleMetadataImports(r)
	case "git_override":
		return gitOverrideImports(r)
	case "archive_override":
		return archiveOverrideImports(r)
	case "single_version_override":
		return singleVersionOverrideImports(r)
	case "local_path_override":
		return localPathOverrideImports(r)
	}
	return nil
}

// Embeds returns a list of labels of rules that the given rule embeds. If a
// rule is embedded by another importable rule of the same language, only the
// embedding rule will be indexed. The embedding rule will inherit the imports
// of the embedded rule. Since SkyLark doesn't support embedding this should
// always return nil.
func (*bcrExtension) Embeds(r *rule.Rule, from label.Label) []label.Label {
	return nil
}

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each rule
// generated by language.GenerateRules in language.GenerateResult.Imports.
// Resolve generates a "deps" attribute (or the appropriate language-specific
// equivalent) for each import according to language-specific rules and
// heuristics.
func (ext *bcrExtension) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	importsRaw any,
	from label.Label,
) {
	cfg := mustGetConfig(c)
	// Switch on rule kind to delegate to specific resolver functions
	switch r.Kind() {
	case "module_dependency":
		resolveModuleDependencyRule(cfg, r, ix, from, ext.moduleToCycle)
	case "module_dependency_cycle":
		resolveModuleDependencyCycleRule(r, ix)
	case "module_metadata":
		resolveModuleMetadataRule(r, ix)
	case "module_registry":
		resolveModuleRegistryRule(r, ix)
	}
}

// GenerateRules extracts build metadata from source files in a directory.
// GenerateRules is called in each directory where an update is requested in
// depth-first post-order.
//
// args contains the arguments for GenerateRules. This is passed as a struct to
// avoid breaking implementations in the future when new fields are added.
//
// A GenerateResult struct is returned. Optional fields may be added to this
// type in the future.
//
// Any non-fatal errors this function encounters should be logged using
// log.Print.
func (ext *bcrExtension) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	cfg := mustGetConfig(args.Config)
	if !cfg.enabled {
		return language.GenerateResult{}
	}

	// log.Println("visiting:", args.Rel, args.RegularFiles)

	var rules []*rule.Rule

	if args.Rel == cfg.modulesRoot {
		// Generate cycles in the modules root package
		cycles := ext.getCycles()
		if len(cycles) > 0 {
			cycleRules := makeModuleDependencyCycleRules(cycles)
			rules = append(rules, cycleRules...)
		}
		// generate registry in the modules root package
		rules = append(rules, makeModuleRegistryRule(cfg.modulesRoot, args.Subdirs))
	}

	if slices.Contains(args.RegularFiles, "metadata.json") {
		filename := filepath.Join(args.Config.WorkDir, args.Rel, "metadata.json")
		md, err := readMetadataJson(filename)
		if err != nil {
			log.Fatalf("reading %s/source.json: %v", args.Rel, err)
		}
		// Generate maintainer rules
		maintainerRules := makeModuleMaintainerRules(md.Maintainers)
		// Add maintainer rules to the list
		rules = append(rules, maintainerRules...)
		// Add metadata rule with references to maintainers
		rules = append(rules, makeModuleMetadataRule(path.Base(args.Rel), md, maintainerRules, "metadata.json"))
	}

	// are we in a module version directory?
	if !inOverlayDir(args.Rel) && slices.Contains(args.RegularFiles, "MODULE.bazel") {
		moduleBazelFilename := filepath.Join(args.Config.WorkDir, args.Rel, "MODULE.bazel")
		module, err := modulebazel.ExecFile(moduleBazelFilename)
		if err != nil {
			log.Fatalf("reading %s: %v", moduleBazelFilename, err)
		}

		// Extract version from path (e.g., modules/foo/1.2.3 -> 1.2.3)
		version := filepath.Base(args.Rel)

		var sourceRule *rule.Rule
		var attestationsRule *rule.Rule
		var presubmitRule *rule.Rule

		if slices.Contains(args.RegularFiles, "source.json") {
			sourceFilename := filepath.Join(args.Config.WorkDir, args.Rel, "source.json")
			source, err := readSourceJson(sourceFilename)
			if err != nil {
				log.Fatalf("reading %s/source.json: %v", args.Rel, err)
			}
			module.Source = source
			sourceRule = makeModuleSourceRule(source, "source.json")
			rules = append(rules, sourceRule)
		}

		if slices.Contains(args.RegularFiles, "attestations.json") {
			// Try to read attestations.json if it exists
			attestationsFilename := filepath.Join(args.Config.WorkDir, args.Rel, "attestations.json")
			attestations, err := readAttestationsJson(attestationsFilename)
			if err != nil {
				log.Fatalf("reading %s/attestations.json: %v", args.Rel, err)
			}
			module.Attestations = attestations
			attestationsRule = makeModuleAttestationsRule(attestations, "attestations.json")
			rules = append(rules, attestationsRule)
		}

		if slices.Contains(args.RegularFiles, "presubmit.yml") {
			// Try to read presubmit.yml if it exists
			presubmitFilename := filepath.Join(args.Config.WorkDir, args.Rel, "presubmit.yml")
			presubmit, err := readPresubmitYaml(presubmitFilename)
			if err != nil {
				log.Printf("reading %s/presubmit.yml: %v", args.Rel, err)
			}
			module.Presubmit = presubmit
			presubmitRule = makeModulePresubmitRule(presubmit, "presubmit.yml")
			rules = append(rules, presubmitRule)
		}

		// Add module to dependency graph
		ext.addModuleToGraph(module.Name, version)
		// Add dependency edges to graph
		for _, dep := range module.Deps {
			ext.addDependencyEdge(module.Name, version, dep.Name, dep.Version)
		}

		// Generate dependency and override rules
		depRules, overrideRules := makeModuleDependencyRules(module.Deps)
		// Add override rules to the list first (so dependencies can reference them)
		rules = append(rules, overrideRules...)
		// Add dependency rules to the list
		rules = append(rules, depRules...)
		// Add module version rule with references to dependencies, source, attestations, and presubmit
		rules = append(rules, makeModuleVersionRule(module, version, depRules, sourceRule, attestationsRule, presubmitRule, "MODULE.bazel"))
	}

	imports := make([]interface{}, len(rules))
	for i, r := range rules {
		imports[i] = r.PrivateAttr(config.GazelleImportsKey)
	}

	return language.GenerateResult{
		Gen:     rules,
		Imports: imports,
	}
}

func inOverlayDir(rel string) bool {
	return strings.Contains(rel, "/overlay")
}
