package bcr

import (
	"flag"
	"log"
	"path/filepath"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/language"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
)

// NewLanguage is called by Gazelle to install this language extension in a
// binary.
func NewLanguage() language.Language {
	return newBcrExtension()
}

// newBcrExtension create a new Gazelle extension implementation.
func newBcrExtension() *bcrExtension {
	return &bcrExtension{}
}

// bcrExtension implements language.Language.
type bcrExtension struct {
	name string
}

// Name returns the name of the language. This should be a prefix of the kinds
// of rules generated by the language, e.g., "go" for the Go extension since it
// generates "go_library" rules.
func (pl *bcrExtension) Name() string {
	return "bcr"
}

// The following methods are implemented to satisfy the
// https://pkg.go.dev/github.com/bazelbuild/bazel-gazelle/resolve?tab=doc#Resolver
// interface, but are otherwise unused.
func (*bcrExtension) RegisterFlags(fs *flag.FlagSet, cmd string, c *config.Config) {
}

func (*bcrExtension) CheckFlags(fs *flag.FlagSet, c *config.Config) error {
	return nil
}

func (*bcrExtension) KnownDirectives() []string {
	return nil
}

// Configure implements config.Configurer
func (pl *bcrExtension) Configure(c *config.Config, rel string, f *rule.File) {
}

// Kinds returns a map of maps rule names (kinds) and information on how to
// match and merge attributes that may be found in rules of those kinds. All
// kinds of rules generated for this language may be found here.
func (*bcrExtension) Kinds() map[string]rule.KindInfo {
	return nil
}

// Loads returns .bzl files and symbols they define. Every rule generated by
// GenerateRules, now or in the past, should be loadable from one of these
// files.
func (pl *bcrExtension) Loads() []rule.LoadInfo {
	return nil
}

// Fix repairs deprecated usage of language-specific rules in f. This is called
// before the file is indexed. Unless c.ShouldFix is true, fixes that delete or
// rename rules should not be performed.
func (*bcrExtension) Fix(c *config.Config, f *rule.File) {
}

// Imports returns a list of ImportSpecs that can be used to import the rule r.
// This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (pl *bcrExtension) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	return nil
}

// Embeds returns a list of labels of rules that the given rule embeds. If a
// rule is embedded by another importable rule of the same language, only the
// embedding rule will be indexed. The embedding rule will inherit the imports
// of the embedded rule. Since SkyLark doesn't support embedding this should
// always return nil.
func (*bcrExtension) Embeds(r *rule.Rule, from label.Label) []label.Label {
	return nil
}

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each rule
// generated by language.GenerateRules in language.GenerateResult.Imports.
// Resolve generates a "deps" attribute (or the appropriate language-specific
// equivalent) for each import according to language-specific rules and
// heuristics.
func (pl *bcrExtension) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	importsRaw any,
	from label.Label,
) {
}

// GenerateRules extracts build metadata from source files in a directory.
// GenerateRules is called in each directory where an update is requested in
// depth-first post-order.
//
// args contains the arguments for GenerateRules. This is passed as a struct to
// avoid breaking implementations in the future when new fields are added.
//
// A GenerateResult struct is returned. Optional fields may be added to this
// type in the future.
//
// Any non-fatal errors this function encounters should be logged using
// log.Print.
func (pl *bcrExtension) GenerateRules(args language.GenerateArgs) language.GenerateResult {
	log.Println("visiting:", args.Rel, args.RegularFiles)

	for _, name := range args.RegularFiles {
		if name == "metadata.json" {
			filename := filepath.Join(args.Config.WorkDir, args.Rel, name)
			_, err := readMetadataJson(filename)
			if err != nil {
				log.Panicln(err)
			}
		}
	}
	return language.GenerateResult{}
}
